services:
  - type: web
    name: nhl-betting
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install --no-cache-dir -r requirements.txt
    startCommand: |
      uvicorn nhl_betting.web.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ODDS_API_KEY
        sync: false
      - key: WEB_READ_ONLY_PREDICTIONS
        value: "true"
      - key: WEB_DISABLE_ODDS_FETCH
        value: "true"
      - key: REFRESH_CRON_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: NIXPACKS_PYTHON_VERSION
        value: 3.11.9
    autoDeploy: true
