services:
  - type: web
    name: nhl-betting
    env: python
    plan: free
    branch: master
    autoDeploy: true
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install --prefer-binary -r requirements.txt
    startCommand: |
      uvicorn nhl_betting.web.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ODDS_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: mostgood1/NHL-Betting
      - key: GITHUB_BRANCH
        value: master
      - key: GITHUB_COMMIT_AUTHOR
        value: Render Bot
      - key: GITHUB_COMMIT_EMAIL
        value: render-bot@example.com
      - key: WEB_READ_ONLY_PREDICTIONS
        value: "true"
      - key: WEB_DISABLE_ODDS_FETCH
        value: "true"
      - key: REFRESH_CRON_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: NIXPACKS_PYTHON_VERSION
        value: 3.11.9
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"

cronJobs:
  - name: nhl-betting-nightly
    schedule: "0 8 * * *"
    command: |
      /bin/sh -lc '
        set -e
        apk add --no-cache curl
        curl -fsS -X POST https://nhl-betting.onrender.com/api/cron/refresh-bovada?date=yesterday -H "Authorization: Bearer ${REFRESH_CRON_TOKEN}" || true
        curl -fsS -X POST https://nhl-betting.onrender.com/api/cron/capture-closing?date=yesterday -H "Authorization: Bearer ${REFRESH_CRON_TOKEN}" || true
        curl -fsS -X POST https://nhl-betting.onrender.com/api/cron/retune -H "Authorization: Bearer ${REFRESH_CRON_TOKEN}" || true
      '
    envVars:
      - key: REFRESH_CRON_TOKEN
        sync: false

  - name: nhl-betting-daytime
    # Every 60 minutes to refresh today's slate; idempotent and only overwrites pre-start games
    schedule: "0 * * * *"
    command: |
      /bin/sh -lc '
        set -e
        apk add --no-cache curl
        curl -fsS -X POST https://nhl-betting.onrender.com/api/cron/refresh-bovada -H "Authorization: Bearer ${REFRESH_CRON_TOKEN}" || true
      '
    envVars:
      - key: REFRESH_CRON_TOKEN
        sync: false

  - name: nhl-betting-props-projections
    # Daily precompute of player props projections; writes props_projections_YYYY-MM-DD.csv and pushes to GitHub
    schedule: "5 12 * * *"
    command: |
      /bin/sh -lc '
        set -e
        apk add --no-cache curl
        # Collect player props lines for today from both sources (best-effort)
        curl -fsS -X POST https://nhl-betting.onrender.com/api/cron/props-collect -H "Authorization: Bearer ${REFRESH_CRON_TOKEN}" || true
        # Compute and persist projections CSV for today (top 1000 rows)
        curl -fsS -X POST "https://nhl-betting.onrender.com/api/cron/props-projections?top=1000" -H "Authorization: Bearer ${REFRESH_CRON_TOKEN}" || true
      '
    envVars:
      - key: REFRESH_CRON_TOKEN
        sync: false

  - name: nhl-betting-props-recommendations
    # Daily precompute of player props recommendations; writes props_recommendations_YYYY-MM-DD.csv and pushes to GitHub
    # Scheduled a few minutes after projections to ensure inputs are ready
    schedule: "10 12 * * *"
    command: |
      /bin/sh -lc '
        set -e
        apk add --no-cache curl
        # Ensure props lines exist (best-effort) then compute and persist recommendations CSV for today
        curl -fsS -X POST https://nhl-betting.onrender.com/api/cron/props-recommendations -H "Authorization: Bearer ${REFRESH_CRON_TOKEN}" || true
      '
    envVars:
      - key: REFRESH_CRON_TOKEN
        sync: false

  - name: nhl-betting-props-full
    # End-to-end props pipeline (lines + projections + recommendations) to ensure artifacts are available daily
    schedule: "20 12 * * *"
    command: |
      /bin/sh -lc '
        set -e
        apk add --no-cache curl
        curl -fsS -X POST https://nhl-betting.onrender.com/api/cron/props-full -H "Authorization: Bearer ${REFRESH_CRON_TOKEN}" || true
      '
    envVars:
      - key: REFRESH_CRON_TOKEN
        sync: false

  - name: nhl-betting-props-all
    # Daily precompute of model-only all-players projections to GitHub
    schedule: "15 12 * * *"
    command: |
      /bin/sh -lc '
        set -e
        apk add --no-cache curl
        curl -fsS -X POST https://nhl-betting.onrender.com/api/cron/props-all -H "Authorization: Bearer ${REFRESH_CRON_TOKEN}" || true
      '
    envVars:
      - key: REFRESH_CRON_TOKEN
        sync: false
