services:
  - type: web
    name: nhl-betting
    env: python
    plan: free
    branch: master
    autoDeployTrigger: commit
    healthCheckPath: /health
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn nhl_betting.web.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ODDS_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: mostgood1/NHL-Betting
      - key: GITHUB_BRANCH
        value: master
      - key: GITHUB_COMMIT_AUTHOR
        value: Render Bot
      - key: GITHUB_COMMIT_EMAIL
        value: render-bot@example.com
      - key: WEB_DISABLE_ODDS_FETCH
        value: "true"
      - key: REFRESH_CRON_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9

  # Nightly maintenance: capture yesterday closings, run retune, and refresh odds.
  - type: cron
    name: nightly-core
    schedule: "0 8 * * *" # 08:00 UTC (~03/04 ET)
    runtime: image
    image:
      url: docker.io/curlimages/curl:8.11.0
    dockerCommand: >
      sh -lc '
        f(){ url="$1"; for i in 1 2 3; do curl -fsS "$url" && return 0; echo "retry $i: $url"; sleep 5; done; return 0; };
        # Capture closings and retune
        f "https://nhl-betting.onrender.com/api/cron/capture-closing?date=yesterday&token=$REFRESH_CRON_TOKEN&async_run=1";
        f "https://nhl-betting.onrender.com/api/cron/retune?token=$REFRESH_CRON_TOKEN&async_run=1";
        # Persist reconciliations for games and props (GET endpoints compute and write caches)
        f "https://nhl-betting.onrender.com/api/reconciliation?date=yesterday";
        f "https://nhl-betting.onrender.com/api/player-props-reconciliation?date=yesterday&refresh=1";
      '
    envVars:
      - key: REFRESH_CRON_TOKEN
        sync: false

  # Daily: Games odds + projections refresh passes (2-3x). Also recomputes edges and recommendations.
  - type: cron
    name: games-refresh-1
    schedule: "30 15 * * *" # 15:30 UTC (~11:30 ET)
    runtime: image
    image:
      url: docker.io/curlimages/curl:8.11.0
    dockerCommand: >
      sh -lc 'curl -fsS "https://nhl-betting.onrender.com/api/refresh-odds?overwrite_prestart=1" || true'

  - type: cron
    name: games-refresh-2
    schedule: "30 18 * * *" # 18:30 UTC (~14:30 ET)
    runtime: image
    image:
      url: docker.io/curlimages/curl:8.11.0
    dockerCommand: >
      sh -lc 'curl -fsS "https://nhl-betting.onrender.com/api/refresh-odds?overwrite_prestart=1" || true'

  - type: cron
    name: games-refresh-3
    schedule: "30 22 * * *" # 22:30 UTC (~18:30 ET)
    runtime: image
    image:
      url: docker.io/curlimages/curl:8.11.0
    dockerCommand: >
      sh -lc 'curl -fsS "https://nhl-betting.onrender.com/api/refresh-odds?overwrite_prestart=1" || true'

  # Daily: Props sequence (collect -> projections_all -> recommendations), 2 passes
  - type: cron
    name: props-refresh-1-collect
    schedule: "35 15 * * *" # 15:35 UTC (~11:35 ET)
    runtime: image
    image:
      url: docker.io/curlimages/curl:8.11.0
    dockerCommand: >
      sh -lc 'curl -fsS -X POST "https://nhl-betting.onrender.com/api/cron/props-collect?token=$REFRESH_CRON_TOKEN&async_run=1" || true'
    envVars:
      - key: REFRESH_CRON_TOKEN
        sync: false

  - type: cron
    name: props-refresh-1-projections-all
    schedule: "40 15 * * *"
    runtime: image
    image:
      url: docker.io/curlimages/curl:8.11.0
    dockerCommand: >
      sh -lc 'curl -fsS -X POST "https://nhl-betting.onrender.com/api/cron/props-all?token=$REFRESH_CRON_TOKEN&async_run=1" || true'
    envVars:
      - key: REFRESH_CRON_TOKEN
        sync: false

  - type: cron
    name: props-refresh-1-recommendations
    schedule: "45 15 * * *"
    runtime: image
    image:
      url: docker.io/curlimages/curl:8.11.0
    dockerCommand: >
      sh -lc 'curl -fsS -X POST "https://nhl-betting.onrender.com/api/cron/props-recommendations?token=$REFRESH_CRON_TOKEN&async_run=1" || true'
    envVars:
      - key: REFRESH_CRON_TOKEN
        sync: false

  - type: cron
    name: props-refresh-2-collect
    schedule: "35 18 * * *" # 18:35 UTC (~14:35 ET)
    runtime: image
    image:
      url: docker.io/curlimages/curl:8.11.0
    dockerCommand: >
      sh -lc 'curl -fsS -X POST "https://nhl-betting.onrender.com/api/cron/props-collect?token=$REFRESH_CRON_TOKEN&async_run=1" || true'
    envVars:
      - key: REFRESH_CRON_TOKEN
        sync: false

  - type: cron
    name: props-refresh-2-projections-all
    schedule: "40 18 * * *"
    runtime: image
    image:
      url: docker.io/curlimages/curl:8.11.0
    dockerCommand: >
      sh -lc 'curl -fsS -X POST "https://nhl-betting.onrender.com/api/cron/props-all?token=$REFRESH_CRON_TOKEN&async_run=1" || true'
    envVars:
      - key: REFRESH_CRON_TOKEN
        sync: false

  - type: cron
    name: props-refresh-2-recommendations
    schedule: "45 18 * * *"
    runtime: image
    image:
      url: docker.io/curlimages/curl:8.11.0
    dockerCommand: >
      sh -lc 'curl -fsS -X POST "https://nhl-betting.onrender.com/api/cron/props-recommendations?token=$REFRESH_CRON_TOKEN&async_run=1" || true'
    envVars:
      - key: REFRESH_CRON_TOKEN
        sync: false
