services:
  - type: web
    name: nhl-betting
    env: python
    plan: starter
    autoDeploy: true
    branch: master
    numInstances: 1
    # Health is served by the lightweight ASGI wrapper and is very fast.
    healthCheckPath: /health
    buildCommand: pip install --no-cache-dir -r requirements.txt
    # Use a lightweight ASGI wrapper and a single worker to keep memory within plan limits.
    startCommand: uvicorn nhl_betting.web.asgi:app --host 0.0.0.0 --port $PORT --workers 1 --log-level info
    envVars:
      - key: ODDS_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: mostgood1/NHL-Betting
      - key: GITHUB_BRANCH
        value: master
      - key: GITHUB_COMMIT_AUTHOR
        value: Render Bot
      - key: GITHUB_COMMIT_EMAIL
        value: render-bot@example.com
      - key: WEB_DISABLE_ODDS_FETCH
        value: "true"
      - key: PROPS_PAGE_SIZE
        value: "100"
      - key: PROPS_MAX_ROWS
        value: "2500"
      - key: CACHED_PROPS_TTL_SECONDS
        value: "300"
      # Limit numeric/BLAS thread counts to reduce memory and context switching on small instances
      - key: OMP_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
      - key: NUMEXPR_NUM_THREADS
        value: "1"
      # Silence ONNX Runtime GPU provider discovery on headless CPU-only hosts
      - key: ORT_DISABLE_TELEMETRY
        value: "1"
      - key: ORT_LOG_SEVERITY_LEVEL
        value: "3"
      - key: CUDA_VISIBLE_DEVICES
        value: "-1"
      # Avoid pip hash enforcement in the Render environment
      - key: PIP_REQUIRE_HASHES
        value: "0"
      - key: WEB_DISABLE_GH_UPSERT
        value: "true"
      - key: WEB_READ_ONLY_PREDICTIONS
        value: "true"
      - key: REFRESH_CRON_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
      # On deploy/restart, do one light odds refresh + edges recompute only
      - key: WEB_ON_DEPLOY_REFRESH_EDGES
        value: "1"

