DEFAULT_UNDER_MIN_EV = 0.18
DEFAULT_UNDER_MAX_JUICE = 170.0
DEFAULT_UNDER_MAX_JUICE_PER_MARKET = "POINTS=120"


__all__ = [
    "DEFAULT_UNDER_MIN_EV",
    "DEFAULT_UNDER_MAX_JUICE",
    "DEFAULT_UNDER_MAX_JUICE_PER_MARKET",
]